### PR TITLE
Updated Readme.txt

### PR DESCRIPTION
**Pull request by aakankshadhurandhar**
I have updated build the application locally and added how we can generate openweather api key

### CODE REVIEW

**Comment by satyammittal** [comment]
@aakankshadhurandhar please fix pep8 issues stated above.

**Comment by satyammittal** [comment]
@aakankshadhurandhar Please keep the readme change only and try to merge in weather feature update done by @Harshini2898

**Comment by aakankshadhurandhar** [comment]
@satyammittal  can you  tell me how to revert back to the version of code before my commit

**Comment by satyammittal** [comment]
@aakankshadhurandhar you can run following commands:

git checkout master
git pull
git checkout <branch>
git rebase

fix conflicts and git commit

**Comment by satyammittal** [comment]
Closing it. Can open again when you fix changes.

**Pull request closed without merging**
